apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: simple-http-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      namespace: project
      labels:
        app: simple-http
    spec:
      volumes:
        - name: simple-http-volume
          persistentVolumeClaim:
            claimName: simple-http-pvc-2-4
      containers:
        # Container for the static server
        - name: simple-http-static
          image: xuanminator/simple-http:2.6-static
          imagePullPolicy: Always
          env:
          - name: STATIC_CACHE_DIR # this is passed to the container
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: STATIC_CACHE_DIR
          - name: STATIC_CACHE_EXPIRY
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: STATIC_CACHE_EXPIRY
          - name: STATIC_BASE_URL
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: STATIC_BASE_URL
          - name: STATIC_TARGET_ID
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: STATIC_TARGET_ID
          - name: STATIC_PORT
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: STATIC_PORT
          # ports:
          # - containerPort: 8060
          volumeMounts:
          - name: simple-http-volume
            mountPath: /tmp/simple-http
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
        # Container for the api server
        - name: simple-http-api
          image: xuanminator/simple-http:2.6-api
          imagePullPolicy: Always
          env:
          - name: API_URI
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: API_URI
          - name: API_PORT
            valueFrom:
              secretKeyRef:
                name: simple-http-secrets
                key: API_PORT
          # ports:
          # - containerPort: 8061
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"