# ingress
# route to service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: simple-http-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-http-svc
                port:
                  number: 2345
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: simple-http-svc
                port:
                  number: 2346
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simple-http-svc
                port:
                  number: 2345
