apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: simple-http-secrets
# apparently, type: opaque + stringData: can be used for k8s native encoding
data:
    API_URI: ENC[AES256_GCM,data:PkeWEA6K,iv:3ULPqEna6eQo9QYaxHbimz87k+lUbwDBv8yhjA7A4ow=,tag:qwiqj6DltmqFjindLStikw==,type:str]
    API_PORT: ENC[AES256_GCM,data:F1lxcg==,iv:31mdtuX3ooxgBKA8kAJtVgNU+t6ggQlt5pxLSkZj1XU=,tag:JWZHbA8vbFjdOHoVJvfIaQ==,type:int]
    STATIC_CACHE_DIR: ENC[AES256_GCM,data:mlARuJHZuCI3fSLx1BN9Pw==,iv:sfmI9CKC+/MK/11BVGBP0/qO3LLClZgK3K+/+55uZsA=,tag:JKoijmu+OlUJdzMUBkERtw==,type:str]
    STATIC_CACHE_EXPIRY: ENC[AES256_GCM,data:OavP,iv:v/kJti0Gjlq6KH/CiMty0Ez5QqGLCEUrHVuFC/5uSUM=,tag:1WDaUn+vsgGDc47ZCo/DcA==,type:int]
    STATIC_BASE_URL: ENC[AES256_GCM,data:KbULHZF/I+h1nEa6Oe96WSRoQdbYUg==,iv:aix7YxezvbhWkO+4bDR9g+FUUjU7Gix4lb8+Brkcpng=,tag:HC5cDfAuJd4wKmBJfkWQjA==,type:str]
    STATIC_TARGET_ID: ENC[AES256_GCM,data:RXVE,iv:NKfzdddkTES544m6OprbgeVoVhsBzAAmstGfAsgM5nU=,tag:9ASJzGTogUGTLvytl6Sffw==,type:int]
    STATIC_PORT: ENC[AES256_GCM,data:uJB/Aw==,iv:KoiRWhiykP981V39M+r1NpKGt9EFOLs04dbn26NbphE=,tag:R49C5FpZ4pj/tYniIThNpg==,type:int]
sops:
    age:
        - recipient: age1aux3je6vdpc8kmfgaj2spdw4r7hj7cwgshcclm58gnj5fsg2x5zs299377
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVm94NW1lcUhWaEFpZ2pQ
            KzZ3eWI1VnkzRi9sSStNVzk2MVAwcGt1dlVFCmFvRDJLdGtyS1FtT25EWDdmbXRx
            elRLbGFmY1pzNEZXMEdFYVNOTFJIZEkKLS0tIDQyR0wralIwVmNtRXJ6OHc1bUNR
            ZmdkSmR0S0FPb25Qd2VCZkN5TGVJOGMK6jnLmxq4DGGiMEpdB8vaXImO9oOsG//A
            4XrYdE1CSbBS/BEfdo87LguFIS/BsNTcVmA4AfItIZ3l45HSdnbEzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T06:32:53Z"
    mac: ENC[AES256_GCM,data:wf9UpooQoibuxFFh6FvXlVKOwyGEPMexjPRVGzcqSSUCsXl7LYdHPds176Hi+BZGdlSu2pkTygEkdiKH+mBC4bn3iHlWYG0JUkIZK7zVZFYD/3gSwbpRwNKSwQHRFZ3DujKmyNfRu7UVlMBEG7PkHrf7zMy2RxYClYA8UzjSgfA=,iv:SW7tqZJdEdaY6p3zxY9ky/4qThkyLX8JA0wCLscdY0w=,tag:Ae3n1alcYfrzZePUK8IAcg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
