apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: simple-http-secrets
# apparently, type: opaque + stringData: can be used for k8s native encoding
data:
  API_URI: L3RvZG9z
  API_PORT: ODA2MQ==
  STATIC_CACHE_DIR: L3RtcC9zaW1wbGUtaHR0cA==
  STATIC_CACHE_EXPIRY: NjAw
  STATIC_BASE_URL: aHR0cHM6Ly9waWNzdW0ucGhvdG9zLw==
  STATIC_TARGET_ID: MTAw
  STATIC_PORT: ODA2MA==