# what do we want? a service
# port to listen to
# application to directed request to
# port to direct to

apiVersion: v1
kind: Service
metadata:
  name: simple-http-svc
# for ingress
spec:
  type: ClusterIP
  selector:
    app: simple-http
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 8060
# for nodeport dev
# spec:
#   type: NodePort
#   selector:
#     app: simple-http
#   ports:
#   - name: http
#     nodePort : 30080 # exposed port
#     protocol: TCP
#     port: 1234 # cluster internal port
#     targetPort: 8060 # application port
