apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: exercises
  name: pv-1-11
spec:
  storageClassName: pv-1-11-storage-class
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube # a path within a node, in this case, agent-0
  nodeAffinity: # only required for local. it's a node selector
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k3d-k3s-default-agent-0