apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
# for ingress
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 8089
# for nodeport dev
# spec:
#   type: NodePort
#   selector:
#     app: simple-http
#   ports:
#   - name: http
#     nodePort : 30080 # exposed port
#     protocol: TCP
#     port: 1234 # cluster internal port
#     targetPort: 8060 # application port
