# This is the same manifest as the one in ping_pong

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-log-shared-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port: 
              number: 2345
      - path: /pingpong
        pathType: ImplementationSpecific
        backend:
          service:
            name: ping-pong-svc
            port: 
              number: 2345
