apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-http-pv-1-13
spec:
  storageClassName: simple-http-pv-1-13-storage-class
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/simple-http
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k3d-k3s-default-agent-0