# The pods seem to share this without problem...?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-http-pvc-1-13
spec:
  storageClassName: simple-http-pv-1-13-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi